url: https://shardul-shah.github.io
baseurl: /agency-fork/

# Site settings
title: Shardul Shah's Portfolio
email: shardul@ualberta.ca
description: A collection of all my projects, ideas, and thoughts.


# Team names, titles and social links
people:
- name: Shardul Shah
  pic: 1
  position: Computer Science Student # edit position to something else * FIXME
  social:
    # uncomment below 2 line when I get twitter account * FIXME
    #- title: twitter
    #  url: #
    #
    # uncomment below 2 lines when I decide to put a facebook account here (if I do) * FIXME
    #- title: facebook
    #  url: #
    - title: stack-overflow 
      url: https://stackoverflow.com/users/5340757/learningcoding
    # change stack-overflow account later * FIXME
    - title: github
      url: https://github.com/shardul-shah

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # uncomment below 4 lines when I decide to use twitter/facebook accounts * FIXME
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  - title: stack-overflow
    url: ttps://stackoverflow.com/users/5340757/learningcoding
  #- title: bitbucket 
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/shardul-shah

# Postal address (add as many lines as necessary)
address:
  - line: Edmonton, Alberta
  - line: Canada

# Build settings
markdown: kramdown
permalink: pretty